version: '3'

services:
  db:
    image: mysql:8.0
    container_name: mysql8
    platform: linux/amd64
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: example 
    ports:
      - "3307:3306" 

  web:
    build: ./backend
    container_name: django
    command: python3 ./backend/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db