version: '3'

services:
  db:
    image: mysql:8.0
    platform: linux/x86_64

  web:
    build: ./backend
    command: python3 ./backend/manage.py runserver 0.0.0.0:8001
    volumes:
      - .:/code
    ports:
      - "8001:8000"
    depends_on:
      - db